name: "meta_config_format_test_with_tags"
time_stamp_name: true
function_name: "test_multi_arg_config"
log_file_path: "local/python_output/RUN_NAME/logs/logs.txt"

wandb_project: "research_scaffold_test"
wandb_group: "meta_config_test"
wandb_tags:
  - "meta_config"
  - "wandb"

function_kwargs:
  root_arg: "read from root.yaml"
  patch_arg: "original read from root.yaml"
  arg2: "default read from root.yaml"